# ================================
# AUTHORITATIVE SERVER
# ================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authoritative-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authoritative
  template:
    metadata:
      labels:
        app: authoritative
    spec:
      containers:
      - name: authoritative
        image: us-central1-docker.pkg.dev/ilzasania-poc/dns-app/authoritative-server:latest
        ports:
        - containerPort: 53533
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: authoritative-service
spec:
  type: NodePort
  selector:
    app: authoritative
  ports:
  - protocol: UDP
    port: 53533
    targetPort: 53533
    nodePort: 30001

# ================================
# FIBONACCI SERVER
# ================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci
  template:
    metadata:
      labels:
        app: fibonacci
    spec:
      containers:
      - name: fibonacci
        image: us-central1-docker.pkg.dev/ilzasania-poc/dns-app/fibonacci-server:latest
        ports:
        - containerPort: 9090
        env:
        - name: UDP_HOST
          value: "authoritative-service"
        - name: UDP_PORT
          value: "53533"
---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci-service
spec:
  type: NodePort
  selector:
    app: fibonacci
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30002

# ================================
# USER SERVER
# ================================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: us-central1-docker.pkg.dev/ilzasania-poc/dns-app/user-server:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30003
